### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by qdrn** [massalabs/docu-dev#113]
We could put all the code examples that are in the docu-dev in an integration tests that would run in the CI. If the CI breaks we would know that we'll have to update the docu-dev. That kind of CI could for example run once per day.

_Originally posted by @julienbrs in https://github.com/massalabs/docu-dev/issues/105#issuecomment-1621427655_

**Comment by julienbrs** [comment]
Logic has changed a bit:
Create end-to-ends test that will be fetched by `docu-dev` and used to display code snippets example for `massa-wb3` page.
These tests will be run on the CI once per day. Thanks to that architecture, if we change the code in the end-to-end tests here,`docu-dev` will be automatically updated.
Each end-to-end test will focus on a subclient API of massa-web3, which means:

- [ ] wallet
- [ ] smart-contracts
- [ ] private-api
- [ ] public-api
