### ISSUE TITLE
Mention Aurélien live coding session

### ISSUE THREAD

**Issue by qdrn** [massalabs/docu-dev#46]
It's probably worth linking the video somewhere as it's probably the most accurate/complete and up to date video tutorial we have.

**Comment by qdrn** [comment]
Maybe @AurelienFT can upload the code somewhere so that people can reproduce ?

**Comment by AurelienFT** [comment]
https://github.com/massalabs/demoyard

**Comment by AurelienFT** [comment]
The link is in the presentation also
