### ISSUE TITLE
Update testnet doc

### ISSUE THREAD

**Issue by qdrn** [massalabs/docu-dev#93]
I'm going to replace the old doc by this one. The testnet doc is probably not up to date with the latest version.

Can you assign someone from your team @AurelienFT ?

**Comment by AurelienFT** [comment]
this one => which one are you speaking about ?
The testnet doc is probably not up to date with the latest version => the one currently on docs.massa.net ?

**Comment by qdrn** [comment]
> this one => which one are you speaking about ?

The doc in this repo (docu-dev)

> The testnet doc is probably not up to date with the latest version => the one currently on docs.massa.net ?

The on in the docu-dev repo.

**Comment by AurelienFT** [comment]
Ok @aoudiamoncef can you check that the doc is up to date please ?

**Comment by aoudiamoncef** [comment]
I synced the API documentation only

**Comment by AurelienFT** [comment]
> I synced the API documentation (JsonRPC/gRPC)

I think @qdrn is talking about the doc of the testnet for node runner : https://github.com/massalabs/docu-dev/tree/main/docs/node

**Comment by aoudiamoncef** [comment]
> > I synced the API documentation (JsonRPC/gRPC)
> 
> I think @qdrn is talking about the doc of the testnet for node runner : [`main`/docs/node](https://github.com/massalabs/docu-dev/tree/main/docs/node?rgh-link-date=2023-06-28T17%3A43%3A43Z)

LGTM, after a quick check based on last commits(timestamps) on https://github.com/massalabs/massa-docs/tree/main/testnet seems that there no modifications.

**Comment by AurelienFT** [comment]
Ok perfect thank you

**Comment by qdrn** [comment]
At least the url of the binaries is wrong (https://massalabs.github.io/docu-dev/docs/node/install). Can you have a closer look please ?

**Comment by AurelienFT** [comment]
@aoudiamoncef can you please check ?

**Comment by aoudiamoncef** [comment]
> At least the url of the binaries is wrong (https://massalabs.github.io/docu-dev/docs/node/install). Can you have a closer look please ?

This should be automated, It's impossible to check all the links one by one each time. 

I'll make this in the CI asap

**Comment by AurelienFT** [comment]
> > At least the url of the binaries is wrong (https://massalabs.github.io/docu-dev/docs/node/install). Can you have a closer look please ?
> 
> We have the same issue in the two docs.
> 
> This should be automated, It's impossible to check all the links one by one each time.
> 
> I'll make this in the CI asap

We don't have the same link in both. In this one it's TEST.22.1 and in our current doc it's TEST.23.2 it shows that the current repository isn't fully updated. that's why @qdrn asked for a deeper check

**Comment by aoudiamoncef** [comment]
May be I did the wrong comparaison ? 

![image](https://github.com/massalabs/docu-dev/assets/22281426/b7a7f3ee-ffbe-4f1b-b041-a9037631409f)

vs 

![image](https://github.com/massalabs/docu-dev/assets/22281426/62b9b341-1edf-4734-9147-eb04239806ef)

https://github.com/massalabs/massa-docs/blob/main/testnet/install.rst
vs 
https://github.com/massalabs/docu-dev/blob/main/docs/node/install.mdx

We have the same content with broken links as in production https://docs.massa.net/en/latest/testnet/install.html

**Comment by AurelienFT** [comment]
No this is not the same content in docu-dev we have the TEST.22.1 version : https://github.com/massalabs/docu-dev/blob/main/docs/node/install.mdx#L49

In production one it's 23.2

**Comment by aoudiamoncef** [comment]
Oh my bad, sorry, I was blind, what should I do to Thyra side ? the links are dead, I know that It's replaced by Massa station

**Comment by AurelienFT** [comment]
For thyra I don't know. But we should be sure that the rest is ok
